config/routes.rb
Databeast::Application.routes.draw do
  get "cards/new"
  resources :users
  resources :cards
  resources :sessions, only: [:new, :create, :destroy]

  root 'pages#home'
  match '/help',     to: 'pages#help',       via: 'get'
  match '/about',    to: 'pages#about',      via: 'get'
  match '/store',    to: 'pages#store',      via: 'get'
  match '/contact',  to: 'pages#contact',    via: 'get'

  match '/signup',   to: 'users#new',        via: 'get'

  match '/signin',   to: 'sessions#new',     via: 'get'
  match '/signout',  to: 'sessions#destroy', via: 'delete'

  match '/newcard',    to: 'card#new',       via: 'get'
  match '/updatecard', to: 'card#update',    via: 'post'
  match '/destroycard', to: 'card#destroy',   via: 'delete'
  match '/search',  to: 'cards#search',   via: 'get'

  

end

app/models/card.rb
class Card < ActiveRecord::Base

	validates :name, presence: true, length: { maximum: 50 },
		uniqueness: { case_sensitive: false }
	validates :price, presence: true
	validates :power_level, presence: true
	validates :health_level, presence: true

	def self.search(search)
		if search
			where(['name LIKE ? OR price LIKE ? OR power_level LIKE ? OR health_level LIKE ?', 
				"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, presence: true, length: { maximum: 50 },
		uniqueness: { case_sensitive: false }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  	@card = Card.new
  end

  def search
    @cards = Card.search(params[:search])
  end

  def create
  	@card = Card.new(card_params)
  	if @card.save
  		flash[:success] = "DataBEAST Datafied"
  		redirect_to @card
  	else
  		render 'new'
  	end
  end

  def show
    if(params[:id] == "all")
      index
    else
      @card = Card.find(params[:id])
    end
  end

  def index
    #@cards = Card.paginate(page: params[:page])
    @cards = Card.search(params[:search])
  end

  def update
  	@card = Card.find(params[:id])
  	if @card.update_attributes(card_params)
  		redirect_to @card
  	else
  		render "edit"
  	end
  end

  def edit
    @card = Card.find(params[:id])
    # if @card.update_attributes(params[:card])
    #   redirect_to @card
    # else
    #   redirect_to 'edit'
    # end
  end


  def destroy
  	Card.find(params[:id]).destroy
    flash.now[:success] = "Beast de-rezzed"
    render "all"
  end

  private 

    def card_params
      params.require(:card).permit(:name, :price, :power_level, :health_level)
    end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def help
	end

	def about
	end

	def store
	end

	def contact
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page])
  end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome, fellow DataBEAST!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private 

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "DataBEAST"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/users_helper.rb
module UsersHelper

	#Returns the Gravatar (http://gravatar.com/) for the given user
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/cards/_card.html.erb
<li>
	<h3><%= link_to card.name, card %></h3>
	Price: <%= card.price %><br>
	Power Level: <%= card.power_level %><br>
	Health Level: <%= card.health_level %>
</li>

app/views/cards/all.html.erb
<% provide(:title, "All Cards") %>
<div class="search">
	
</div>
<div class="cards">
	<h1>All Cards</h1>
	<% Card.all.each do |card| %>
		<h3><%= link_to card.name, card %></h3>
		<h4>PRICE: <%= card.price %><br>
		POWER LEVEL: <%= card.power_level %><br>
		HEALTH LEVEL: <%= card.health_level %><br></h4>
	<% end %>
</div>

<%= link_to "Create a new card", new_card_path, class: 'btn btn-large btn-primary' %>

app/views/cards/edit.html.erb
<% provide(:title, 'Edit a card') %>
<h1>Edit a DataBEAST</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@card) do |f| %>
			<%= render 'shared/error_messages', entity: @card %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :price %>
			<%= f.text_field :price %>

			<%= f.label :power_level %>
			<%= f.text_field :power_level %>

			<%= f.label :health_level %>
			<%= f.text_field :health_level %>

			<%= f.submit "Fix this BEAST", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/cards/index.html.erb
<% provide(:title, "All Cards") %>
<div class="search">
	
</div>
<ul class="cards">
	<%= render @cards %>
</ul>

<%= link_to "Create a new card", new_card_path, class: 'btn btn-large btn-primary' %>

app/views/cards/new.html.erb
<% provide(:title, 'Create a card') %>
<h1>Create a New DataBEAST</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@card) do |f| %>
			<%= render 'shared/error_messages', entity: @card %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :price %>
			<%= f.text_field :price %>

			<%= f.label :power_level %>
			<%= f.text_field :power_level %>

			<%= f.label :health_level %>
			<%= f.text_field :health_level %>

			<%= f.submit "Create this BEAST", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/cards/search.html.erb
<% provide(:title, "Search") %>

<%= form_tag cards_path, :method => 'get' do %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag("Search Name", :name => nil, class: 'btn btn-large btn-primary') %>
<% end %>

<%= form_tag cards_path, :method => 'get' do %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search Price", :price => nil, class: 'btn btn-large btn-primary'%>
<% end %>

<%= link_to "Back to all", cards_path, class: 'btn btn-large btn-primary' %>

<ul class="cards">
	<%= render @cards %>
</ul>

<%= link_to "Create a new card", new_card_path, class: 'btn btn-large btn-primary' %>

app/views/cards/searchname.html.erb
<% provide(:title, "All Cards") %>
<div class="search">
	<%= check_box_tag(:card_name) %>
	<%= label_tag(:card_name, "Name") %>
	<%= check_box_tag(:card_price) %>
	<%= label_tag(:card_price, "Price") %>
	<%= check_box_tag(:card_power_level) %>
	<%= label_tag(:card_power_level, "Power Level") %>
	<%= check_box_tag(:card_health_level) %>
	<%= label_tag(:card_health_level, "Health Level") %> 
</div>

<%= form_tag("/searchname", method: "get") do %>
	<%= label_tag(:q, "Name Search:") %>
	<%= text_field_tag :name_search, params[:search] %>
	<%= submit_tag("Search", class: 'btn btn-large btn-primary') %>
<% end %>

<%= form_tag("/searchprice", method: "get") do %>
	<%= label_tag(:q, "Price Search:") %>
	<%= text_field_tag :price_search, params[:search] %>
	<%= submit_tag("Search", class: 'btn btn-large btn-primary') %>
<% end %>

<%= link_to "Back to all", cards_path, class: 'btn btn-large btn-primary' %>


<ul class="cards">
	<%= render @cards %>
</ul>

<%= link_to "Create a new card", new_card_path, class: 'btn btn-large btn-primary' %>

app/views/cards/searchprice.html.erb
<% provide(:title, "All Cards") %>
<div class="search">
	<%= check_box_tag(:card_name) %>
	<%= label_tag(:card_name, "Name") %>
	<%= check_box_tag(:card_price) %>
	<%= label_tag(:card_price, "Price") %>
	<%= check_box_tag(:card_power_level) %>
	<%= label_tag(:card_power_level, "Power Level") %>
	<%= check_box_tag(:card_health_level) %>
	<%= label_tag(:card_health_level, "Health Level") %> 
</div>

<%= form_tag("/searchname", method: "get") do %>
	<%= label_tag(:q, "Name Search:") %>
	<%= text_field_tag :name_search, params[:search] %>
	<%= submit_tag("Search", class: 'btn btn-large btn-primary') %>
<% end %>

<%= form_tag("/searchprice", method: "get") do %>
	<%= label_tag(:q, "Price Search:") %>
	<%= text_field_tag :price_search, params[:search] %>
	<%= submit_tag("Search", class: 'btn btn-large btn-primary') %>
<% end %>

<%= link_to "Back to all", cards_path, class: 'btn btn-large btn-primary' %>


<ul class="cards">
	<%= render @cards %>
</ul>

<%= link_to "Create a new card", new_card_path, class: 'btn btn-large btn-primary' %>

app/views/cards/show.html.erb
<% provide(:title, @card.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= @card.name %>
			</h1>
			<ul>
				<li>PRICE: <%= @card.price %></li>
				<li>POWER LEVEL: <%= @card.power_level %></li>
				<li>HEALTH LEVEL: <%= @card.health_level %></li>
			</ul>
		</section>
	</aside>
</div>

<%= link_to "Edit", edit_card_path(@card), class: "btn btn-large btn-primay" %>

<%= link_to "Delete", @card, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-large btn-primary" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Site by Ryan March and Nick Mazzeo
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",   about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "databeast", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",	 root_path %></li>
					<li><%= link_to "Help",  help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Cards", cards_path %></li>
						<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
	This is the about page for the Databeasts
</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	This is the contact page for the Databeasts
</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Welcome to the DataBEAST help page
</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
	<h1>DataBEAST</h1>

	<h2>
		This is the home page for the DataBEAST site
	</h2>

	<%= link_to "Sign up now", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/pages/store.html.erb
<% provide(:title, 'Store') %>
<h1>Store</h1>
<p>
	Welcome to the Store page of the Databeast Site
</p>

app/views/shared/_error_messages.html.erb
<% if entity.errors.any? %>
	<div id="error_explanation">
		<div class="aler alert-error">
			The form contains <%= pluralize(entity.errors.count, "error") %>
		</div>		
		<ul>
			<% entity.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user %>
	<%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', entity: @user %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>